name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: |
          npm install
          cd express-app && npm install

      - name: Build Angular
        run: ng build --configuration=production

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/angular/*,express-app/*"
          target: "/home/${{ secrets.REMOTE_USER }}/app"
          strip_components: 1

      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directories if they don't exist
            mkdir -p ~/app/frontend
            mkdir -p ~/app/backend
            
            # Install pm2 locally if not installed
            if ! command -v ~/node_modules/.bin/pm2 &> /dev/null; then
              npm install pm2 --prefix ~/
            fi
            
            # Deploy Angular app
            cp -r ~/app/angular/* ~/app/frontend/
            
            # Deploy Express app
            cp -r ~/app/express-app/* ~/app/backend/
            cd ~/app/backend
            npm install
            
            # Start/Restart the Express app with PM2
            ~/node_modules/.bin/pm2 describe express-app > /dev/null
            if [ $? -eq 0 ]; then
              ~/node_modules/.bin/pm2 restart express-app
            else
              cd ~/app/backend && ~/node_modules/.bin/pm2 start app.js --name express-app
            fi
            
            # Clean up
            rm -rf ~/app/angular ~/app/express-app